#!/usr/bin/env bash
echo "
===============
|  Running detekt...
===============
"

./gradlew --no-daemon --stacktrace :app:lintKotlin

lintStatus=$?
echo "detektStatus Result :"
if [ "$lintStatus" = 0 ]; then
    echo "No issues were found, committing changes."
    exit 0
else
    echo 1>&2 "Need to fix issues before commit."
    exit 1
fi